import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import type { MetabaseClient } from "../client.js";
import type { Config } from "../config.js";
import { registerSearchTools } from "./search.js";
import { registerDatabaseTools } from "./databases.js";
import { registerTableTools } from "./tables.js";
import { registerCollectionTools } from "./collections.js";
import { registerCardTools } from "./cards.js";
import { registerDashboardTools } from "./dashboards.js";
import { registerActionTools } from "./actions.js";
import { registerDatasetTools } from "./dataset.js";
import { registerUserTools } from "./users.js";
import { registerPermissionTools } from "./permissions.js";
import { registerSegmentTools } from "./segments.js";
import { registerRevisionTools } from "./revisions.js";
import { registerSettingTools } from "./settings.js";
import { registerNotificationTools } from "./notifications.js";
import { registerXrayTools } from "./xrays.js";
import { registerCacheTools } from "./cache.js";
import { registerPersistenceTools } from "./persistence.js";
import { registerUploadTools } from "./upload.js";
import { registerActivityTools } from "./activity.js";
import { registerSnippetTools } from "./snippets.js";
import { registerGlossaryTools } from "./glossary.js";
import { registerDocumentTools } from "./documents.js";
import { registerTimelineTools } from "./timelines.js";
import { registerBookmarkTools } from "./bookmarks.js";
import { registerModerationTools } from "./moderation.js";
import { registerEidTranslationTools } from "./eid-translation.js";

export const registerAllTools = (server: McpServer, client: MetabaseClient, config: Config) => {
  registerSearchTools(server, client);
  registerDatabaseTools(server, client, config);
  registerTableTools(server, client, config);
  registerCollectionTools(server, client, config);
  registerCardTools(server, client, config);
  registerDashboardTools(server, client, config);
  registerActionTools(server, client, config);
  registerDatasetTools(server, client);
  registerUserTools(server, client, config);
  registerPermissionTools(server, client, config);
  registerSegmentTools(server, client, config);
  registerRevisionTools(server, client, config);
  registerSettingTools(server, client, config);
  registerNotificationTools(server, client, config);
  registerXrayTools(server, client);
  registerCacheTools(server, client, config);
  registerPersistenceTools(server, client, config);
  registerUploadTools(server, client, config);
  registerActivityTools(server, client);
  registerSnippetTools(server, client, config);
  registerGlossaryTools(server, client, config);
  registerDocumentTools(server, client, config);
  registerTimelineTools(server, client, config);
  registerBookmarkTools(server, client, config);
  registerModerationTools(server, client, config);
  registerEidTranslationTools(server, client);
};
